root = "."
tmp_dir = "cmd/api/tmp"

[build]
# Added -gcflags for debugging support
cmd = "go build -gcflags='all=-N -l' -o cmd/api/tmp/main ./cmd/api/main.go"
bin = "cmd/api/tmp/main"
# Modified full_bin to use delve for debugging
full_bin = "dlv exec --accept-multiclient --log --headless --continue --listen :2345 --api-version 2 ./cmd/api/tmp/main"
# Watch these filename extensions.
include_ext = ["go", "tpl", "tmpl", "html", "env", "yaml", "yml", "json"]
# Ignore these filename extensions or directories.
exclude_dir = ["assets", "cmd/api/tmp", "vendor"]
# Watch these directories if you specified.
include_dir = []
# Exclude files.
exclude_file = []
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 500 # ms
# Stop to run old binary when build errors occur.
stop_on_error = true
# This log file places in your tmp_dir.
log = "cmd/api/tmp/air_errors.log"

[log]
# Show log time
time = true

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true